// Artworks
export const SET_PORTFOLIO_CATEGORIES = 'SET_PORTFOLIO_CATEGORIES'
export const SET_SELECTED_PORTFOLIO_CATEGORY = 'SET_SELECTED_PORTFOLIO_CATEGORY'
export const APPEND_ARTWORKS_TO_CATEGORY = 'APPEND_ARTWORKS_TO_CATEGORY'
export const SET_SELECTED_PORTFOLIO_ARTWORK = 'SET_SELECTED_PORTFOLIO_ARTWORK'
export const NAVIGATE_ARTWORK = 'NAVIGATE_ARTWORK'

// Bibliography
export const SET_BIBL_SECTION = 'SET_BIBL_SECTION'
export const ADD_OEUVRES = 'ADD_OEUVRES'
export const PUSH_OEUVRES = 'PUSH_OEUVRES'
export const ADD_BIBL_SERIES = 'ADD_BIBL_SERIES'
export const SET_SELECTED_SERIE = 'SET_SELECTED_SERIE'