// Artworks
export const SET_PORTFOLIO_CATEGORIES = 'SET_PORTFOLIO_CATEGORIES'
export const SET_SELECTED_PORTFOLIO_CATEGORY = 'SET_SELECTED_PORTFOLIO_CATEGORY'
export const APPEND_ARTWORKS_TO_CATEGORY = 'APPEND_ARTWORKS_TO_CATEGORY'
export const SET_SELECTED_PORTFOLIO_ARTWORK = 'SET_SELECTED_PORTFOLIO_ARTWORK'
export const NAVIGATE_ARTWORK = 'NAVIGATE_ARTWORK'